### ISSUE TITLE
implement nil pointer check for nokia submodules

### ISSUE THREAD

**Issue by hellt** [hellt/yangpath#5]
```
yangpath export -m nokia-conf-router-bgp.yang

panic: runtime error: invalid memory address or nil pointer dereference

[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x510a78]

goroutine 1 [running]:
github.com/openconfig/goyang/pkg/yang.ToEntry(0xa2bce0, 0xc00031a000, 0xc0000a2300)
        /home/runner/go/pkg/mod/github.com/openconfig/goyang@v0.0.0-20200803193518-78bac27bdff1/pkg/yang/entry.go:699 +0x33d8
github.com/openconfig/goyang/pkg/yang.(*Modules).Process(0xc0000e9350, 0xc0000e9380, 0xc000115cd0, 0x0)
        /home/runner/go/pkg/mod/github.com/openconfig/goyang@v0.0.0-20200803193518-78bac27bdff1/pkg/yang/modules.go:332 +0x3a6
github.com/hellt/yangpath/cmd.glob..func1(0xd5d4c0, 0xc0000cd060, 0x0, 0x2, 0x0, 0x0)
        /home/runner/work/yangpath/yangpath/cmd/export.go:51 +0x30c
github.com/spf13/cobra.(*Command).execute(0xd5d4c0, 0xc0000cd040, 0x2, 0x2, 0xd5d4c0, 0xc0000cd040)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842 +0x460
github.com/spf13/cobra.(*Command).ExecuteC(0xd5d760, 0x43b3aa, 0xd22100, 0xc00004c750)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x349
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
github.com/hellt/yangpath/cmd.Execute()
        /home/runner/work/yangpath/yangpath/cmd/root.go:33 +0x31
main.main()
        /home/runner/work/yangpath/yangpath/main.go:20 +0x20
```

**Comment by hellt** [comment]
as per 152b71ca6131249f0afdcc30d3920a85527b4f30 the path extraction from submodules is not supported
